import { ActivityType } from "../pods/activity-list";

export const ACTIVITIES: ActivityType[] = [
  {
    id: 1,
    assistants: 13,
    association: "GENT",
    category: "games",
    city: "Barcelona",
    time: new Date(),
    title: "Jocs de taula",
  },
  {
    id: 2,
    assistants: 7,
    category: "sports",
    city: "Barcelona",
    time: new Date(),
    title: "Caminata",
  },
  {
    id: 3,
    assistants: 4,
    category: "social",
    city: "Esplugues de Llobregat",
    time: new Date(),
    title: "Bailem swing",
  },
  {
    id: 4,
    assistants: 11,
    association: "GENT",
    category: "sports",
    city: "Sant Just Desvern",
    time: new Date(),
    title: "Trobada en el parc",
  },
  {
    id: 5,
    assistants: 8,
    category: "social",
    city: "Barcelona",
    time: new Date(),
    title: "Prenem un café",
  },
  {
    id: 6,
    assistants: 13,
    association: "GENT",
    category: "games",
    city: "Barcelona",
    time: new Date(),
    title: "Jocs de taula",
  },
  {
    id: 7,
    assistants: 7,
    category: "sports",
    city: "Barcelona",
    time: new Date(),
    title: "Caminata",
  },
];
